name : 03 - Workflow Runners
on:
 push
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
          - name: Using the Checkout Action
            uses: actions/checkout@v4
          - name: Printing Folders 
            run: ls
